update to OpenRewrite 8.23.2 + specify maven-surefire-plugin version as 2.22.0 to workaround java.lang.NoSuchMethodError: 'java.util.Set org.junit.platform.engine.TestDescriptor.getAncestors() test failure
Signed-off-by: Scott Marlow <smarlow@redhat.com>